export const INITIAL_LEADS = [
  {
    id: "LD-2026-001",
    name: "Suresh Radhakrishnan",
    mobile: "+91 98765 43210",
    whatsapp: "+91 98765 43210",
    alternateMobile: "+91 98765 00112",
    address: "Flat 402, Oakwood Towers, Juhu",
    city: "Mumbai",
    product: "Premium Solid Wood Dining Table (6-Seater)",
    budget: 85000,
    source: "Instagram",
    socialUsername: "@suresh_radha",
    message:
      "Saw your post about premium oak dining tables. Need customization for teak polish.",
    assignedTo: "Amit Sharma",
    followUpDate: "2026-05-27",
    priority: "Hot",
    status: "Negotiation",
    notes:
      "Wants premium velvet upholstery for chairs. Sending quote tomorrow morning.",
    tags: ["High-Budget", "Living Room"],
    timeline: [
      {
        date: "2026-05-25 10:30 AM",
        user: "System",
        text: "Lead captured from Instagram ad campaign.",
      },
      {
        date: "2026-05-25 11:15 AM",
        user: "Amit Sharma",
        text: "Called client. Expressed high interest. Sent catalogue.",
      },
      {
        date: "2026-05-26 03:00 PM",
        user: "Amit Sharma",
        text: "Requested customized polish sample details.",
      },
    ],
  },
  {
    id: "LD-2026-002",
    name: "Aditi Rao",
    mobile: "+91 91234 56789",
    whatsapp: "+91 91234 56789",
    alternateMobile: "",
    address: "Villa 22, Green Meadows Layout",
    city: "Bengaluru",
    product: "Nilkamal Novella Premium Lounger Sofas",
    budget: 120000,
    source: "Walk-in Customers",
    socialUsername: "",
    message:
      "Visited Indiranagar showroom. Checked out L-shaped leatherette lounge sets.",
    assignedTo: "Priya Nair",
    followUpDate: "2026-05-26",
    priority: "Hot",
    status: "Interested",
    notes:
      "Requires home layout inspection before shipping. Floor planner needs to visit.",
    tags: ["Luxury Sofa", "Showroom Guest"],
    timeline: [
      {
        date: "2026-05-24 02:00 PM",
        user: "System",
        text: "Walk-in registration at Bangalore South Branch.",
      },
      {
        date: "2026-05-24 04:30 PM",
        user: "Priya Nair",
        text: "Showed live samples. She preferred modern tan layout.",
      },
    ],
  },
  {
    id: "LD-2026-003",
    name: "Rajesh Malhotra",
    mobile: "+91 93456 78901",
    whatsapp: "+91 93456 78901",
    alternateMobile: "+91 93322 11004",
    address: "B-104, Regency Park, DLF Phase 4",
    city: "Gurugram",
    product: "Ergonomic Mesh Office Chairs (Bulk 15 Units)",
    budget: 180000,
    source: "Website Inquiry",
    socialUsername: "",
    message:
      "Inquiry from Corporate Office for brand new seating arrangement setup.",
    assignedTo: "Vikram Rathore",
    followUpDate: "2026-05-28",
    priority: "Warm",
    status: "Contacted",
    notes: "Requested corporate discount and warranty terms certificate.",
    tags: ["Bulk Purchase", "Office Mesh"],
    timeline: [
      {
        date: "2026-05-23 09:12 AM",
        user: "System",
        text: "B2B contact form submitted on website.",
      },
      {
        date: "2026-05-24 11:00 AM",
        user: "Vikram Rathore",
        text: "Corporate pitch document emailed.",
      },
    ],
  },
  {
    id: "LD-2026-004",
    name: "Komal Deshmukh",
    mobile: "+91 98111 22233",
    whatsapp: "+91 98111 22233",
    alternateMobile: "",
    address: "Apt 9C, Sea Breeze Heights, Bandra",
    city: "Mumbai",
    product: "Nilkamal Freedom Plastic Wardrobe Set",
    budget: 15000,
    source: "Phone Calls",
    socialUsername: "",
    message:
      "Enquiring about lightweight, heavy-duty weather-proof bedroom cabinet.",
    assignedTo: "Riya Sen",
    followUpDate: "2026-05-25",
    priority: "Cold",
    status: "Follow-up Pending",
    notes:
      "Wants home delivery. Follow-up today missed. High priority to reschedule.",
    tags: ["Plastic Cabinet", "Home Storage"],
    timeline: [
      {
        date: "2026-05-22 05:40 PM",
        user: "Riya Sen",
        text: "Call received. Explained warranty structure of resin series.",
      },
    ],
  },
  {
    id: "LD-2026-005",
    name: "Dr. Anand Sen",
    mobile: "+91 95432 10987",
    whatsapp: "+91 95432 10987",
    alternateMobile: "",
    address: "Senior Housing Block B, Salt Lake",
    city: "Kolkata",
    product: "Motorized Premium Recliner Chair",
    budget: 45000,
    source: "Referral Leads",
    socialUsername: "",
    message:
      "Referred by Dr. Bannerjee. Prefers automatic leather recliner with orthopaedic foam support.",
    assignedTo: "Priya Nair",
    followUpDate: "2026-05-29",
    priority: "Hot",
    status: "Converted",
    notes:
      "Ordered & advanced payment finalized! Preparing shipment documentation.",
    tags: ["Recliner Chair", "Referral High Value"],
    timeline: [
      {
        date: "2026-05-21 11:00 AM",
        user: "Priya Nair",
        text: "Client demo arranged via Zoom.",
      },
      {
        date: "2026-05-23 04:00 PM",
        user: "Priya Nair",
        text: "Advanced payment of INR 15,000 received. Marked Converted.",
      },
    ],
  },
  {
    id: "LD-2026-006",
    name: "Nikhil Mehra",
    mobile: "+91 99991 88882",
    whatsapp: "+91 99991 88882",
    alternateMobile: "",
    address: "H-401, Golf Links Extension",
    city: "New Delhi",
    product: "Modular King-Size Teakwood Bed with Storage",
    budget: 95000,
    source: "Facebook",
    socialUsername: "nikhil.mehra.fb",
    message:
      "Interested in Nilkamal Premium bedroom setups. Needs custom hydraulic lifters.",
    assignedTo: "Amit Sharma",
    followUpDate: "2026-05-30",
    priority: "Warm",
    status: "New",
    notes: "Sent price catalogue and custom design sheets. Waiting response.",
    tags: ["Teak Wood Bed", "Storage Beds"],
    timeline: [
      {
        date: "2026-05-26 09:30 AM",
        user: "System",
        text: "Lead imported from Facebook Lead Form (Bedroom campaign).",
      },
    ],
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: "EMP-001",
    name: "Amit Sharma",
    role: "Sales Executive",
    activeLeads: 12,
    convertedLeads: 34,
    target: 450000,
    currentSales: 380000,
    status: "Active",
    avatar: "AS",
  },
  {
    id: "EMP-002",
    name: "Priya Nair",
    role: "Manager",
    activeLeads: 8,
    convertedLeads: 42,
    target: 600000,
    currentSales: 590000,
    status: "Active",
    avatar: "PN",
  },
  {
    id: "EMP-003",
    name: "Vikram Rathore",
    role: "Sales Executive",
    activeLeads: 15,
    convertedLeads: 28,
    target: 400000,
    currentSales: 290000,
    status: "Active",
    avatar: "VR",
  },
  {
    id: "EMP-004",
    name: "Riya Sen",
    role: "Telecaller",
    activeLeads: 22,
    convertedLeads: 19,
    target: 200000,
    currentSales: 165000,
    status: "Active",
    avatar: "RS",
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    title: "Overdue Follow-up",
    msg: "Komal Deshmukh's phone follow-up is overdue.",
    time: "2 hrs ago",
    unread: true,
    category: "warning",
  },
  {
    id: 2,
    title: "New Lead Assigned",
    msg: "New Lead 'Nikhil Mehra' assigned to Amit Sharma via Facebook API.",
    time: "4 hrs ago",
    unread: true,
    category: "info",
  },
  {
    id: 3,
    title: "Campaign Completed",
    msg: "Pre-Monsoon Dining Campaign reached 4,500 contacts successfully.",
    time: "1 day ago",
    unread: false,
    category: "success",
  },
];

export const INITIAL_CAMPAIGNS = [
  {
    id: "CMP-001",
    name: "Monsoon Sofa Discount Blast",
    createdBy: "Priya Nair",
    sentDate: "2026-05-15",
    audienceSize: 4500,
    status: "Completed",
    sent: 4500,
    delivered: 4420,
    read: 3850,
    replied: 890,
    failed: 80,
    clicked: 1205,
    template: "Promotional Sofa Offer",
    media: "Sofa_Discount_Banner.jpg",
    deliveryPercent: 98.2,
    replyRate: 19.7,
  },
  {
    id: "CMP-002",
    name: "Teakwood Bed Exclusive Invite",
    createdBy: "Amit Sharma",
    sentDate: "2026-05-20",
    audienceSize: 3200,
    status: "Completed",
    sent: 3200,
    delivered: 3110,
    read: 2900,
    replied: 512,
    failed: 90,
    clicked: 814,
    template: "Luxury Bed Invitation",
    media: "Teakwood_Bed_Catalog.pdf",
    deliveryPercent: 97.1,
    replyRate: 16.0,
  },
  {
    id: "CMP-003",
    name: "Plastic Storage Solutions Campaign",
    createdBy: "Riya Sen",
    sentDate: "2026-05-24",
    audienceSize: 1850,
    status: "Completed",
    sent: 1850,
    delivered: 1812,
    read: 1540,
    replied: 245,
    failed: 38,
    clicked: 322,
    template: "Cabinet Clearance Offer",
    media: "Freedom_Cabinet_PriceList.png",
    deliveryPercent: 97.9,
    replyRate: 13.2,
  },
  {
    id: "CMP-004",
    name: "Active Hydration - Recliner VIP Followup",
    createdBy: "Vikram Rathore",
    sentDate: "2026-05-27",
    audienceSize: 4010,
    status: "Draft",
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    failed: 0,
    clicked: 0,
    template: "Premium Recliner Auto-Drip",
    media: "None",
    deliveryPercent: 0,
    replyRate: 0,
  },
];

export const REUSABLE_TEMPLATES = [
  {
    id: "TMP-01",
    name: "Promotional Sofa Offer",
    category: "Promotional",
    language: "English (en_US)",
    status: "Approved",
    body: "Hello {{customer_name}}, Nilkamal Furniture brings special premium living room collections for you! Enjoy a flat 15% OFF on our best-selling sofa sets. Click below to view catalog: {{catalog_link}}",
    buttons: ["View Collection 🛋️", "Stop Promos"],
  },
  {
    id: "TMP-02",
    name: "Teakwood Bed Exclusive Invite",
    category: "New Arrival",
    language: "English (en_US)",
    status: "Approved",
    body: "Dear {{customer_name}}, explore pure elegance. Nilkamal introduces our finest seasoned solid teakwood beds. Comes with 10-years factory warranty. Reserve a free showroom demo slot in {{city}} today!",
    buttons: ["Book Demo Slot 📅", "Talk to Designer"],
  },
  {
    id: "TMP-03",
    name: "Follow-Up & Maintenance Reminder",
    category: "Utility",
    language: "English (en_US)",
    status: "Approved",
    body: "Hi {{customer_name}}, this is {{sales_executive}} from Nilkamal. We noticed you checked out our ergonomic mesh chairs last week. Need custom lumber-support sizing or bulk discounts? Text us back anytime!",
    buttons: ["Connect with Agent 🤝", "Maybe Later"],
  },
  {
    id: "TMP-04",
    name: "Festival Greetings Blast",
    category: "Marketing",
    language: "English (en_US)",
    status: "Approved",
    body: "Warm greetings {{customer_name}}! May this seasonal holiday bring peace to your home. Enjoy exclusive pre-access holiday markdowns of 20% on all Nilkamal home furnishings. Safe shipping guaranteed.",
    buttons: ["Unlock VIP Discount 🔓", "Unsubscribe"],
  },
];

export const INITIAL_WHATSAPP_CHATS = [
  {
    id: "WA-101",
    name: "Nitin Singhania",
    phone: "+91 98888 77777",
    unread: true,
    typing: false,
    assignedTo: "Amit Sharma",
    product: "Premium Novella Accent Chairs",
    budget: 45000,
    priority: "Hot",
    status: "Interested",
    tags: ["High Budget", "Living Room"],
    messages: [
      {
        sender: "customer",
        text: "Hello! Saw your WhatsApp ad. Do you have premium lounge armchairs in green velvet option?",
        time: "11:15 AM",
      },
      {
        sender: "agent",
        text: "Hi Nitin! Yes, we have our Novella Armchair in premium velvet green. It comes with mahogany support legs. Shall I send photos?",
        time: "11:20 AM",
      },
      {
        sender: "customer",
        text: "Yes please, also share the warranty details and estimated price with shipping to Bandra, Mumbai.",
        time: "11:25 AM",
      },
    ],
  },
  {
    id: "WA-102",
    name: "Meera Patel",
    phone: "+91 97777 66666",
    unread: false,
    typing: false,
    assignedTo: "Priya Nair",
    product: "Modular Hydraulic King Bed",
    budget: 110000,
    priority: "Hot",
    status: "Negotiation",
    tags: ["Bedroom", "Premium Teak"],
    messages: [
      {
        sender: "customer",
        text: "Can you provide custom dimensions of 6x6.5 feet for the storage bed?",
        time: "09:40 AM",
      },
      {
        sender: "agent",
        text: "Hi Meera, absolutely! We can customize the frame layout size at our factory. It takes 10 working days.",
        time: "09:45 AM",
      },
      {
        sender: "customer",
        text: "Excellent. Let me discuss the fabric shades with my interior planner and get back.",
        time: "10:02 AM",
      },
    ],
  },
];
